package org.torrent.coredata;

public class FlowControls {

	public static enum TorrentStatus{
		CONTACTING_TRACKER,
		MESSAGING_PEERS
	}
	
	public static enum ChannelStatus {
		CONTACTING_TRACKER,
		MESSAGING_TRACKER,
		SENDING_HANDSHAKE,
		WAITING_HANDSHAKE,
		WAITING_TRACKER_RESPONSE,
		SENDING_BITFIELD,
		WAITING_BITFIELD,
		CHECKING_FOR_PIECE,
		PROCESSING_MESSAGES,
		LISTENING_TO_PEER,
		LISTENING_FOR_BITFIELD,
		SENDING_HANDSHAKE_BITFIELD,
	}
	
}
